import Head from 'next/head'
import Header from "../components/Header";
import Banner from "../components/Banner";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";
import LargeCard from "../components/LargeCard";

export default function Home({exploreData, cardsData }) {
  // console.log(exploreData)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
            <Banner/>

            <main className={'max-w-7xl mx-auto px-8 sm:px-10'}>
                <section className={'pt-6'}>
                    <h2 className={'text-4xl font-semibold pb-5'}>Explore Nearby</h2>
                    <div className={'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'}>
                        {
                            exploreData.map((item) => (
                                // eslint-disable-next-line react/jsx-key
                                <SmallCard key={item.img} img={item.img} distance={item.distance} location={item.location}/>
                            ))
                        }
                    </div>
                </section>

                <section>
                    <h2 className={'text-4xl font-semibold py-8'}>Live Anywhere</h2>
                   <div className={'flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'}>
                       {cardsData.map((item) => (
                           <MediumCard img={item.img} title={item.title} key={item.img} />
                       )) }
                   </div>
                </section>
                <section>
                    <LargeCard
                        img={'https://a0.muscache.com/im/pictures/2da67c1c-0c61-4629-8798-1d4de1ac9291.jpg?im_w=1440'}
                        title={'The greatest Outdoors'}
                        description={'Wishlist curated by Airbnb'}
                        buttonText={'Get Inspired'}
                    />
                </section>

                </main>
    </div>
  )
}

export async function getStaticProps() {
  const data = await fetch('https://www.jsonkeeper.com/b/4G1G')
  const exploreData = await  data.json();
  const dataForCards = await fetch('https://www.jsonkeeper.com/b/VHHT')
  const cardsData = await dataForCards.json()


    return {
        props: {
            exploreData,
            cardsData,
        }
    }
}
